#%RAML 1.0 NamedExample
{
    "response": {
        "message": "convert lead successful",
        "payload": {
            "contactId": "003Hq00003BYZsHIAX",
            "accountId": "001Hq00003J4zygIAB",
            "opportunityId": null,
            "success": true,
            "errors": [],
            "leadId": "00QHq00001iiGmNMAU"
        }
    }
}