#%RAML 1.0 NamedExample
{
    "response": {
        "message": "create lead successful",
        "createdlead": [
            {
                "id": "00QHq00001iiFf4MAE",
                "status": true
            },
            {
                "id": "00QHq00001iiFf5MAE",
                "status": true
            }
        ]
    }
}