#%RAML 1.0 NamedExample
{
    "response": {
        "message": "get lead successful for Bertha Boxer",
        "payload": [
            {
                "Id": "00Q3600000B0rTwEAJ",
                "type": "Lead",
                "Name": "Bertha Boxer"
            }
        ]
    }
}