#%RAML 1.0 NamedExample
{
    "response": {
        "message": "retrieve ten random leads",
        "payload": [
            {
                "Id": "00Q3600000B0rTwEAJ",
                "type": "Lead",
                "Name": "Bertha Boxer"
            },
            {
                "Id": "00Q3600000B0rTxEAJ",
                "type": "Lead",
                "Name": "Phyllis Cotton"
            },
            {
                "Id": "00Q3600000B0rTyEAJ",
                "type": "Lead",
                "Name": "Jeff Glimpse"
            },
            {
                "Id": "00Q3600000B0rTzEAJ",
                "type": "Lead",
                "Name": "Mike Braund"
            },
            {
                "Id": "00Q3600000B0rU0EAJ",
                "type": "Lead",
                "Name": "Patricia Feager"
            },
            {
                "Id": "00Q3600000B0rU1EAJ",
                "type": "Lead",
                "Name": "Brenda Mcclure"
            },
            {
                "Id": "00Q3600000B0rU2EAJ",
                "type": "Lead",
                "Name": "Violet Maccleod"
            },
            {
                "Id": "00Q3600000B0rU3EAJ",
                "type": "Lead",
                "Name": "Kathy Snyder"
            },
            {
                "Id": "00Q3600000B0rU4EAJ",
                "type": "Lead",
                "Name": "Tom James"
            },
            {
                "Id": "00Q3600000B0rUAEAZ",
                "type": "Lead",
                "Name": "Kristen Akin"
            }
        ]
    }
}