#%RAML 1.0 NamedExample
[
    {
        "Id": "00QHq00001iiFezMAE",
        "type": "Lead",
        "Name": "John-1 Doe"
    },
    {
        "Id": "00QHq00001iiFf0MAE",
        "type": "Lead",
        "Name": "John-2 Doe"
    },
    {
        "Id": "00QHq00001iiFf4MAE",
        "type": "Lead",
        "Name": "John-1 Doe"
    },
    {
        "Id": "00QHq00001iiFf5MAE",
        "type": "Lead",
        "Name": "John-2 Doe"
    }
]