#%RAML 1.0
title: estore-sfdc-system-api

/ping:
  get:
    description: ping
    responses:
      200:
        body:
          application/json:
            type: object
            examples:
              example1: !include examples/ping-response.raml

/lead:
  post:
    description: create lead
    body:
        application/json:
          example: |
            [
                {
                    "firstname": "John-1",
                    "lastname": "Doe",
                    "company": "Atlanta Products",
                    "status": "Open"
                },
                {
                    "firstname": "John-2",
                    "lastname": "Doe",
                    "company": "Atlanta Products",
                    "status": "Open"
                }
            ]
    responses:
      200:
        body:
          application/json:
            type: object
            examples:
              example1: !include examples/create-lead-response.raml
  get:
     queryParameters:
      leadname:
        description: leadname
        type: string
        required: false
      company:
        description: company
        type: string
        required: false
     description: getlead
     responses:
      200:
        body:
          application/json:
              type: object
              examples:
                example1: !include examples/get-lead-by-id-response.raml
                example2: !include examples/get-random-ten-lead-response.raml
                example3: !include examples/get-lead-by-name-response.raml
  /{Id}:
    get:
      description: get lead by Id
      responses:
        200:
          body:
            application/json:
              type: object
              examples:
                example1: !include examples/get-lead-by-id-response.raml
/convertlead:
  post:
    description: convert lead
    body:
        application/json:
          example: |
            {
              "name": "John Doe Atlanta",
              "leadsource": "web",
              "doNotCreateOpportunity": false
            }
    responses:
      200:
        body:
          application/json:
              type: object
              examples:
                example1: !include examples/convert-lead-response.raml
          
/deleteleads:
  post:
    description: delete leads
    body:
        application/json:
          example: |
            {
              "leadidsfordelete": ["00QHq00001iiFdhMAE", "00QHq00001iiFdiMAE"],
              "callsource": "postman"
            }
    responses:
      200:
        body:
          application/json:
          
/deleteaccountcontact:
  post:
    description: delete Account and Contact
    body:
        application/json:
          example: |
            {
              "acct_contact_idsfordelete": ["00QHq00001iiFdhMAE", "00QHq00001iiFdiMAE"],
              "callsource": "postman"
            }
    responses:
      200:
        body:
          application/json:
/leadstaticquery:
  get:
     queryParameters:
      leadname:
        description: leadname
        type: string
        required: false
      company:
        description: company
        type: string
        required: false
     description: getlead
     responses:
      200:
        body:
          application/json:
            examples:
              example1: !include examples/get-lead-static-by-company-response.raml
              example2: !include examples/get-lead-static-by-leadname-response.raml
              
/product:
  post:
    description: create product
    body:
        application/json:
          example: |
            [
                {
                    "Name": "test-book-1",
                    "description": "test book 1"
                },
                {
                   "Name": "test-book-2",
                    "description": "test book 2"
                }
            ]
    responses:
      200:
        body:
          application/json:

  /{Id}:
    get:
      description: get product by Id
      responses:
        200:
          body:
            application/json:
/deleteproducts:
  post:
    description: delete products
    body:
        application/json:
          example: |
            {
              "productidsfordelete": ["00QHq00001iiFdhMAE", "00QHq00001iiFdiMAE"],
              "callsource": "postman"
            }
    responses:
      200:
        body:
          application/json:
/productsbyproductcodelist:
  post:
    description: get products by product code list
    body:
        application/json:
          example: |
            {
              "productcodelist": ["ABC-SPC-R01", "ABC-SPG-01", "ABC-SPG-02"],
              "callsource": "postman"
            }
    responses:
      200:
        body:
          application/json:
/pricebookentry:
  post:
    description: create product
    body:
        application/json:
          example: |
                [
                  {
                    "productcode": "ABC-SPC-R01",
                    "currency": "EUR",
                    "pricebookname": "Standard Price Book",
                    "price": "397"
                  }
                ]
    responses:
      200:
        body:
          application/json:
  get:
     queryParameters:
      productcode:
        description: productcode
        type: string
        required: true
      pricebookname:
        description: pricebookname
        type: string
        required: true
     description: get pricebook entries
     responses:
      200:
        body:
          application/json:
/pricebookentrycurrency:
  get:
     queryParameters:
      productcode:
        description: productcode
        type: string
        required: false
      pricebookname:
        description: pricebookname
        type: string
        required: true
      currencycode:
        description: currencycode
        type: string
        required: false
     description: get pricebook entries
     responses:
      200:
        body:
          application/json:
/deletepricebookentry:
  post:
    description: delete pricebookentry
    body:
        application/json:
          example: |
            {
              "pricebookentryfordelete": ["00QHq00001iiFdhMAE", "00QHq00001iiFdiMAE"],
              "callsource": "postman"
            }
    responses:
      200:
        body:
          application/json:
          
/opportunity:
  get:
     queryParameters:
      opportunityname:
        description: opportunity name
        type: string
        required: true
     description: get opportunity
     responses:
      200:
        body:
          application/json:
  /{Id}:
    put:
      description: update opportunity
      body:
          application/json:
            example: |
              {
                  "opportunitycurrency": "JPY",
                  "opportunitypricebook": "Enterprise"
              }
  /product:
    post:
      description: create opportunity product
      body:
          application/json:
            example: |
                  {
                    "opportunityname": "Saito - Ground-mounted Panels",
                    "products": [
                        {
                          "productcode": "SPG-01",
                          "quantity": 35
                        },
                        {
                          "productcode": "SPG-02",
                          "quantity": 20
                        }
                    ]
                  }
      responses:
        200:
          body:
            application/json:
  /removeproduct:
    post:
      description: delete opportunity product
      body:
          application/json:
            example: |
                  {
                    "opportunityname": "Saito - Ground-mounted Panels",
                    "products": [
                        {
                          "productcode": "SPG-01",
                          "quantity": 35
                        },
                        {
                          "productcode": "SPG-02",
                          "quantity": 20
                        }
                    ]
                  }
      responses:
        200:
          body:
            application/json:
  /quote:
    get:
       queryParameters:
        opportunityname:
          description: opportunity name
          type: string
          required: true
       description: get quotes on the opportunity
       responses:
        200:
          body:
            application/json:
    post:
      description: create quote for the opportunity
      body:
          application/json:
            example: |
                  {
                    "opportunityname": "Saito - Ground-mounted Panels",
                    "quotename": "test-quote-1"
                  }
      responses:
        200:
          body:
            application/json:
/deletequotes:
  post:
    description: delete products
    body:
        application/json:
          example: |
            {
              "quoteidsfordelete": ["0Q0bm0000003a6zCAA", "0Q0bm0000003a8bCAA"],
              "callsource": "postman"
            }
    responses:
      200:
        body:
          application/json:
/account:
  get:
     queryParameters:
      accountname:
        description: accouunt name
        type: string
        required: true
     description: get account
     responses:
      200:
        body:
          application/json:
  /{Id}:
    put:
      description: update account
      body:
          application/json:
            example: |
              {
                  "accountcurrency": "JPY"
              }
  /contract:
    get:
       queryParameters:
        accountname:
          description: account name
          type: string
          required: true
       description: get contracts on the opportunity
       responses:
        200:
          body:
            application/json:
    post:
      description: create contract for the account
      body:
          application/json:
            example: |
              {
                  "accountname": "Boy Scouts of the Southwest",
                  "contracts": [
                      {
                          "contractstartdate": "07-02-2024",
                          "contractterm": "12"
                      },
                      {
                          "contractstartdate": "07-02-2025",
                          "contractterm": "12"
                      }
                  ]
              }
      responses:
        200:
          body:
            application/json:
/order:
    get:
     queryParameters:
      contractnumber:
        description: contract number
        type: string
        required: true
     description: get orders for the contracts
     responses:
      200:
        body:
          application/json:
    post:
      description: create orders for the contract
      body:
          application/json:
            example: |
              {
                  "contractnumber": "00000110",
                  "opportunityname": "BSofSW - Ground-mounted Panels"
              }
      responses:
        200:
          body:
            application/json:
/deletecontracts:
  post:
    description: delete contracts
    body:
        application/json:
          example: |
            {
              "contractidsfordelete": ["0Q0bm0000003a6zCAA", "0Q0bm0000003a8bCAA"],
              "callsource": "postman"
            }
    responses:
      200:
        body:
          application/json:
/deleteorders:
  post:
    description: delete orders
    body:
        application/json:
          example: |
            {
              "orderidsfordelete": ["0Q0bm0000003a6zCAA", "0Q0bm0000003a8bCAA"],
              "callsource": "postman"
            }
    responses:
      200:
        body:
          application/json:
