#%RAML 1.0
title: estore-sfdc-system-api

/ping:
  get:
    description: ping
    responses:
      200:
        body:
          application/json:
            type: object
            examples:
              example1: !include examples/ping-response.raml

/lead:
  post:
    description: create lead
    body:
        application/json:
          example: |
            [
                {
                    "firstname": "John-1",
                    "lastname": "Doe",
                    "company": "Atlanta Products",
                    "status": "Open"
                },
                {
                    "firstname": "John-2",
                    "lastname": "Doe",
                    "company": "Atlanta Products",
                    "status": "Open"
                }
            ]
    responses:
      200:
        body:
          application/json:
            type: object
            examples:
              example1: !include examples/create-lead-response.raml
  get:
     queryParameters:
      leadname:
        description: leadname
        type: string
        required: false
      company:
        description: company
        type: string
        required: false
     description: getlead
     responses:
      200:
        body:
          application/json:
              type: object
              examples:
                example1: !include examples/get-lead-by-id-response.raml
                example2: !include examples/get-random-ten-lead-response.raml
                example3: !include examples/get-lead-by-name-response.raml
  /{Id}:
    get:
      description: get lead by Id
      responses:
        200:
          body:
            application/json:
              type: object
              examples:
                example1: !include examples/get-lead-by-id-response.raml
/convertlead:
  post:
    description: convert lead
    body:
        application/json:
          example: |
            {
              "name": "John Doe Atlanta",
              "leadsource": "web",
              "doNotCreateOpportunity": false
            }
    responses:
      200:
        body:
          application/json:
              type: object
              examples:
                example1: !include examples/convert-lead-response.raml
          
/deleteleads:
  post:
    description: delete leads
    body:
        application/json:
          example: |
            {
              "leadidsfordelete": ["00QHq00001iiFdhMAE", "00QHq00001iiFdiMAE"],
              "callsource": "postman"
            }
    responses:
      200:
        body:
          application/json:
          
/deleteaccountcontact:
  post:
    description: delete Account and Contact
    body:
        application/json:
          example: |
            {
              "acct_contact_idsfordelete": ["00QHq00001iiFdhMAE", "00QHq00001iiFdiMAE"],
              "callsource": "postman"
            }
    responses:
      200:
        body:
          application/json:
/leadstaticquery:
  get:
     queryParameters:
      leadname:
        description: leadname
        type: string
        required: false
      company:
        description: company
        type: string
        required: false
     description: getlead
     responses:
      200:
        body:
          application/json:
            examples:
              example1: !include examples/get-lead-static-by-company-response.raml
              example2: !include examples/get-lead-static-by-leadname-response.raml
              
/product:
  post:
    description: create product
    body:
        application/json:
          example: |
            [
                {
                    "Name": "test-book-1",
                    "description": "test book 1"
                },
                {
                   "Name": "test-book-2",
                    "description": "test book 2"
                }
            ]
    responses:
      200:
        body:
          application/json:

  /{Id}:
    get:
      description: get product by Id
      responses:
        200:
          body:
            application/json:
/deleteproducts:
  post:
    description: delete products
    body:
        application/json:
          example: |
            {
              "productidsfordelete": ["00QHq00001iiFdhMAE", "00QHq00001iiFdiMAE"],
              "callsource": "postman"
            }
    responses:
      200:
        body:
          application/json:
